name: "Determine Build Tools JS"
description: "Processes build aggregation data to determine required installation."
inputs:
  build_data_json:
    description: "The JSON string of the aggregated build results."
    required: true
outputs:
  INSTALL_RUST_TOOLS:
    description: 'Output "true" if any Rust task did NOT complete with a cache hit.'
  INSTALL_JS_TOOLS:
    description: 'Output "true" if any TypeScript task did NOT complete with a cache hit.'

runs:
  using: "node20"
  main: "index.js"
