[package]
name = "omni_projection_configurations"
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
version = "0.1.0"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
omni_types = { workspace = true }
omni_config_types = { workspace = true }
omni_glob = { workspace = true }
omni_glob_config = { workspace = true }
enum-map = { workspace = true }
strum = { workspace = true }
lazy-regex = { workspace = true }
serde_validate = { workspace = true }
