[package]
name = "serde_validate"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
version = "0.3.0"

[lib]
path = "src/lib.rs"

# [[bench]]
# path = "./benches/omni_generator_benchmarks.rs"
# name = "omni_generator_benchmarks"
# harness = false

[features]
default = ["enable-tracing"]
enable-tracing = ["trace/enabled", "dep:tracing"]

[dependencies]
trace = { workspace = true }
tracing = { workspace = true, optional = true }
serde = { workspace = true }
