import baseConfig from "@omni-oss/oxfmt-config/base";
import { defineConfig } from "oxfmt";

export default defineConfig({
    ...baseConfig,
    ignorePatterns: [
        "./**/__generated__/**/*",
        "./**/gen/**/*",
        "./**/routeTree.gen.ts",
        "./**/styled-system/**/*",
        "./**/styled-system-studio/**/*",
        "./**/.cache/**/*",
        "./**/.git/**/*",
        "./**/.svn/**/*",
        "./**/node_modules/**/*",
        "./**/dist/**/*",
        "./**/bin/**/*",
        "./**/build/**/*",
        "./**/_build/**/*",
        "./**/_server/**/*",
        "./**/coverage/**/*",
        "./**/public/*.*",
        "./**/.next/*.*",
        "./**/out/*.*",
        "./**/output/*.*",
        "./**/.output/*.*",
        "./**/.obj/*.*",
        "./**/.turbo/*.*",
        "**/turbo.lock",
        "**/yarn.lock",
        "**/package-lock.json",
        "**/pnpm-lock.yaml",
        "**/pnpm-workspace.yaml",
        "**/yarn-error.log",
        "**/lerna.json",
        "**/bun.lock",
        "**/tsconfig.json",
        "**/tsconfig.tsbuildinfo",
        "**/*.tsbuildinfo",
        "**/*.config.js",
        "./**/*.gen.*",
        "./**/*.generated.*",
        "./**/bin/**/*",
        "**/render/html/template.html",
        ".omni/**/*.*",
        "**/CHANGELOG.md",
        "CHANGELOG.root.md",
    ],
    overrides: [
        {
            files: ["**.yaml", "**.yml"],
            options: {
                tabWidth: 2,
            },
        },
    ],
});
