[package]
name = "omni_glob"
rust-version.workspace = true
edition.workspace = true
version = "0.0.0"
authors.workspace = true
repository.workspace = true

[lib]
name = "omni_glob"
path = "src/lib.rs"

[features]
default = []
serde = ["dep:serde", "omni_types/serde"]

[dependencies]
globset = { workspace = true }
omni_types = { workspace = true, default-features = false }
omni_utils = { workspace = true }
serde = { workspace = true, optional = true }
