[package]
name = "omni_expressions"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
version = "0.1.0"

[lib]
path = "src/lib.rs"

[[bench]]
path = "./benches/omni_expressions_benchmarks.rs"
name = "omni_expressions_benchmarks"
harness = false

[features]
default = ["serde" ]
serde = ["dep:serde"]

[dependencies]
thiserror = { workspace = true }
derive-new = { workspace = true }
eyre = { workspace = true }
strum = { workspace = true }
serde = { workspace = true, optional = true }
cel = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
test-log = { workspace = true }
