// The router factory shared by the client boot (src/App.tsx), the per-request
// SSR setup (src/setup.tsx), and the single-flight collector
// (src/server-config.ts), so all three routers are identical.
import type { QueryClient } from "@tanstack/solid-query";
import { createRouter } from "@tanstack/solid-router";
import { setupRouterSsrQueryIntegration } from "@tanstack/solid-router-ssr-query";

import { createQueryClient } from "./lib/queries";
// Generated by @tanstack/router-plugin from the files under src/routes.
import { routeTree } from "./routeTree.gen";

// Router context, received by every loader: carrying the QueryClient here is
// the idiomatic Router + Query pairing.
export interface RouterContext {
    queryClient: QueryClient;
}

export function getRouter() {
    const queryClient = createQueryClient();
    const router = createRouter({
        routeTree,
        context: { queryClient },
        // Hovering (or touching) a <Link> runs the target route's loader early.
        defaultPendingComponent: () => <main>Loading…</main>,

        defaultStaleTime: 0,
        scrollRestoration: true,
        defaultPreload: "intent",
    });

    setupRouterSsrQueryIntegration({
        queryClient,
        router,
    });

    return router;
}

// Registers the router's types library-wide (typed `to`/`params` on <Link>).
declare module "@tanstack/solid-router" {
    interface Register {
        router: ReturnType<typeof getRouter>;
    }
}
