[package]
name = "omni_remote_cache_service"
rust-version.workspace = true
edition.workspace = true
version = "0.0.0-semantically-released"
authors.workspace = true
repository.workspace = true

[dependencies]
async-trait = { workspace = true }
eyre = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
trace = { workspace = true }
tracing = { workspace = true }
derive-new = { workspace = true }
derive_builder = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
axum-valid = { workspace = true }
axum-extra = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_norway = { workspace = true }
bytes = { workspace = true }
bytesize = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
omni_remote_cache_storage = { workspace = true }
omni_tracing_subscriber = { workspace = true }
rust-embed = { workspace = true, features = ["compression", "include-exclude", "deterministic-timestamps", "axum-ex"] }
utoipa = { workspace = true }
utoipa-scalar = { workspace = true }
shadow-rs = { workspace = true }
bs58 = { workspace = true }
tokio-util = { workspace = true }
tokio-stream = { workspace = true }
omni_path_utils = { workspace = true }
schemars = { workspace = true }
maps = { workspace = true }
sets = { workspace = true }
time = { workspace = true }

[build-dependencies]
eyre = { workspace = true }
shadow-rs = { workspace = true, features = ["default"] }
