name: "Package Jobs Artifacts"
description: "Package Jobs Artifacts, archives task outputs one by one and collects into a single folder"

inputs:
  jobs:
    description: "Jobs to package"
    required: true
  target:
    description: "Target platform if applicable"
    required: false
  outdir:
    description: "Output directory"
    required: false
    default: "artifacts"

outputs:
  artifacts_list:
    description: "List of artifacts"
    value: ${{ steps.collect.outputs.artifacts_list }}

runs:
  using: "composite"
  steps:
    - name: Collect Artifacts
      id: collect
      uses: actions/github-script@v8
      env:
        JOBS_JSON: ${{ inputs.jobs }}
        TARGET: ${{ inputs.target }}
        OUTDIR: ${{ inputs.outdir }}
        WORKSPACE_ROOT: ${{ github.workspace }}
      with:
        script: |
          const fs = require('node:fs');
          const path = require('node:path');

          const jobs = JSON.parse(process.env.JOBS_JSON);
          const target = process.env.TARGET;
          const repoRoot = process.env.GITHUB_WORKSPACE;
          const isWindows = process.platform === 'win32';

          const outdir = path.isAbsolute(process.env.OUTDIR)
              ? process.env.OUTDIR
              : path.join(repoRoot, process.env.OUTDIR);

          const createdZips = [];
          await fs.promises.mkdir(outdir, { recursive: true });

          const getZipName = (artifact) => target
              ? `${artifact.name}_${target}.zip`
              : `${artifact.name}.zip`;

          for (const job of jobs) {
              const { project_dir, artifacts } = job;
              const categories = [
                  { data: artifacts.workspace, base: repoRoot },
                  { data: artifacts.project, base: project_dir }
              ];

              for (const cat of categories) {
                  if (cat.data && cat.data.files_count > 0) {
                      const zipName = getZipName(cat.data);
                      const zipPath = path.join(outdir, zipName);

                      const globber = await glob.create(cat.data.files.join('\n'), { matchDirectories: false });
                      const files = await globber.glob();

                      if (files.length > 0) {
                          const relativeFiles = files.map(f => path.relative(cat.base, f));

                          if (isWindows) {
                              // Windows: Use PowerShell Compress-Archive
                              // We join files with commas for the PowerShell array syntax
                              const filesList = relativeFiles.map(f => `'${f}'`).join(',');
                              const psCommand = `Compress-Archive -Path ${filesList} -DestinationPath '${zipPath}' -Force`;
                              await exec.exec('powershell', ['-Command', psCommand], { cwd: cat.base });
                          } else {
                              // Unix: Use standard zip utility
                              await exec.exec('zip', ['-r9', zipPath, ...relativeFiles], { cwd: cat.base });
                          }

                          createdZips.push(zipPath);
                      }
                  }
              }
          }

          core.setOutput('artifacts', createdZips.join('\n'));
          core.setOutput('artifacts_count', createdZips.length.toString());

    - if: ${{ steps.collect.outputs.artifacts_count > 0 }}
      name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: artifacts
        path: ${{ steps.collect.outputs.artifacts }}
