name: "Package Jobs Artifacts"
description: "Package Jobs Artifacts, archives task outputs one by one and collects into a single folder"

inputs:
  jobs:
    description: "Jobs to package"
    required: true
  target:
    description: "Target platform if applicable"
    required: false
  outdir:
    description: "Output directory"
    required: false
    default: "artifacts"

outputs:
  artifacts_list:
    description: "List of artifacts"
    value: ${{ steps.collect.outputs.artifacts_list }}

runs:
  using: "composite"
  steps:
    - run: npm install archiver glob
      shell: bash

    - name: Collect Artifacts
      id: collect
      uses: actions/github-script@v8
      env:
        JOBS_JSON: ${{ inputs.jobs }}
        TARGET: ${{ inputs.target }}
        OUTDIR: ${{ inputs.outdir }}
        WORKSPACE_ROOT: ${{ github.workspace }}
      with:
        script: |
          // github-script (node20)

          const fs = require('node:fs');
          const path = require('node:path');
          const glob = require('glob');
          const archiver = require('archiver');

          const jobs = JSON.parse(process.env.JOBS_JSON); // JSON string
          const target = process.env.TARGET;
          const repoRoot = process.env.GITHUB_WORKSPACE;

          // OUTDIR can be relative or absolute
          const outdir = path.isAbsolute(process.env.OUTDIR || '')
            ? process.env.OUTDIR
            : path.join(repoRoot, process.env.OUTDIR || 'artifacts');

          const createdZips = [];

          function resolveFiles(patterns) {
            return patterns.flatMap(p =>
              glob.sync(p, { nodir: true, windowsPathsNoEscape: true })
            );
          }

          async function zipFiles(zipPath, files, baseDir) {
            await fs.promises.mkdir(path.dirname(zipPath), { recursive: true });

            const output = fs.createWriteStream(zipPath);
            const archive = archiver('zip', { zlib: { level: 9 } });

            archive.pipe(output);

            for (const file of files) {
              const relativePath = path.relative(baseDir, file);
              archive.file(file, { name: relativePath });
            }

            await archive.finalize();
          }

          await fs.promises.mkdir(outdir, { recursive: true });

          function getZipName(artifact) {
            return target
                ? `${artifact.name}_${target}.zip`
                : `${artifact.name}.zip`;
          };

          for (const job of jobs) {
            const { project_dir, artifacts } = job;

            // 1) Workspace-level artifact (relative to repo root)
            if (artifacts.workspace.files_count > 0) {
              const files = resolveFiles(artifacts.workspace.files);
              if (files.length > 0) {
                const zipName = getZipName(artifacts.workspace);
                const zipPath = path.join(outdir, zipName);

                await zipFiles(zipPath, files, repoRoot);
                createdZips.push(zipPath);
              }
            }

            // 2) Project-level artifact (relative to project_dir)
            if (artifacts.project.files_count > 0) {
              const files = resolveFiles(artifacts.project.files);
              if (files.length > 0) {
                const zipName = getZipName(artifacts.project);
                const zipPath = path.join(outdir, zipName);

                await zipFiles(zipPath, files, project_dir);
                createdZips.push(zipPath);
              }
            }
          }

          // Output JSON array string
          core.setOutput('artifacts_list', JSON.stringify(createdZips));
          console.log(`Created ${createdZips.length} zip files in ${outdir}:`, createdZips);
