[package]
name = "omni_task_executor"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
repository.workspace = true

[features]
default = ["enable-tracing"]
enable-tracing = ["dep:tracing", "dep:trace", "trace/enabled"]

[dependencies]
eyre = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
omni_core = { workspace = true }
atty = { workspace = true }
trace = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
shlex = { workspace = true }
omni_hasher = { workspace = true }
system_traits = { workspace = true }
bytes = { workspace = true }
derive-new = { workspace = true }
futures = { workspace = true }
maps = { workspace = true }
env = { workspace = true }
omni_configurations = { workspace = true }
omni_expressions = { workspace = true }
omni_context = { workspace = true }
globset = { workspace = true }
config_utils = { workspace = true }
derive_builder = { workspace = true }
getset = { workspace = true }
