[package]
name = "omni_remote_cache_client"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
repository.workspace = true

[features]
enable-tracing = ["trace/enabled"]

[dependencies]
eyre = { workspace = true }
thiserror = { workspace = true }
strum = { workspace = true }
serde = { workspace = true }
derive-new = { workspace = true }
derive_builder = { workspace = true }
trace = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
bytesize = { workspace = true }
tokio = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
reqwest = { workspace = true }
