name: "Setup Omni"
description: "Setup Omni"
inputs:
  cache-key-prefix:
    description: "Additional text to prepend to cache keys"
    required: false
    default: "global"
  cache-restore-key-prefixes:
    description: "Additional text to prepend to cache restore keys"
    required: false
  shell:
    description: "Shell to use"
    required: false
    default: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
  github-token:
    description: "GitHub token for higher rate limit"
    required: false
    default: ${{ github.token }}
  version:
    description: "Version of Omni to install"
    required: false
    default: "v0.7.0" # most stable version

runs:
  using: "composite"
  steps:
    - name: Install Omni
      uses: omni-oss/setup-omni@v1
      with:
        github-token: ${{ inputs.github-token }}
        version: ${{ inputs.version }}

    - name: Get Workspace Hash
      id: get_workspace_hash
      run: echo "workspace_hash=$(omni hash -r workspace)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create Restore Key List
      shell: bash
      id: create_restore_key_list
      env:
        RAW_RESTORE_KEY_LIST: ${{ inputs.cache-restore-key-prefixes }}
        CACHE_KEY_PREFIX: ${{ inputs.cache-key-prefix }}
        RUNNER_OS: ${{ runner.os }}
      run: |
        # check if $RAW_RESTORE_KEY_LIST is empty
        if [ -z "$RAW_RESTORE_KEY_LIST" ]; then
          res="${RUNNER_OS}-omni-${CACHE_KEY_PREFIX}-"
          echo "restore_key_list<<EOF" >> "$GITHUB_OUTPUT"
          echo "$res" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
        else
          # Define a literal newline
          NL=$'\n'

          for prefix in $RAW_RESTORE_KEY_LIST; do
            # Use the variable for clean concatenation
            res="${res}${NL}${RUNNER_OS}-omni-$prefix-"
          done

          res="${res}${NL}${RUNNER_OS}-omni-"

          echo "restore_key_list<<EOF" >> "$GITHUB_OUTPUT"
          echo "$res" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
        fi
        echo "Restore Key List: $res"

    - name: Cache Omni directory
      uses: actions/cache@v4
      with:
        path: |
          .omni
        key: ${{ runner.os }}-omni-${{ inputs.cache-key-prefix }}-${{ steps.get_workspace_hash.outputs.workspace_hash }}
        restore-keys: ${{ steps.create_restore_key_list.outputs.restore_key_list }}
