[package]
name = "omni_utils"
rust-version.workspace = true
edition.workspace = true
version = "0.2.0"
authors.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]
system_traits = { workspace = true, features = [
    "real-sync",
    "real-async-tokio",
    "memory-sync",
    "memory-async",
] }
bs58 = { workspace = true }
globset = { workspace = true }
maps = { workspace = true }
path-clean = { workspace = true }
pathdiff = { workspace = true }
tokio = { workspace = true }
