name: Preview Site

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        description: "Version to publish"
  push:
    branches:
      - main
    paths:
      - "apps/site/**"

permissions:
  contents: write

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Omni
        uses: ./.github/actions/setup-omni
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
          cache-key-prefix: docs
          version: ${{ github.event.inputs.version || 'latest' }}

      - name: Setup Tools
        uses: ./.github/actions/setup-tools
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          install-bun: true
          install-node-modules: true
          install-node: true

      - name: Install Vercel CLI
        run: bun add -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}

      - name: Generate Docs
        run: omni run -p '@repo/site' build

      - name: Publish Docs
        run: vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }} --cwd ./apps/site
