name: Publish Docs

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        description: "Version to publish"

  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: "latest"
        description: "Version to publish"

permissions:
  contents: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Omni
        uses: ./.github/actions/setup-omni
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
          omni-cache-key-prefix: build

      - name: Setup Tools
        uses: ./.github/actions/setup-tools
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          install-bun: true
          install-node-modules: true
          install-node: true

      - name: Publish Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: .
          keep_files: true
