name: Publish JSON Schemas

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        description: "Version to publish"

  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: "latest"
        description: "Version to publish"
    secrets:
      GITHUB_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  publish-json-schemas:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Omni
        uses: omni-oss/setup-omni@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN || github.token }}

      - name: Generate JSON Schemas
        shell: bash
        run: |
          mkdir -p ./json-schemas
          INSTALLED_VERSION=$(omni --version | cut -d' ' -f2)

          # loop through all the json schemas and publish them
          schemas=("project" "workspace" "generator")
          for schema in "${schemas[@]}"; do
            echo "Publishing $schema schema..."
            
            omni config print-schema $schema >| "./json-schemas/$schema-$INSTALLED_VERSION.json"
            omni config print-schema $schema >| "./json-schemas/$schema-latest.json"
          done

      - name: Publish JSON Schemas
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: json-schemas
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./json-schemas
          destination_dir: .
          keep_files: true
